version: "3.7"
services:

  playerdb:
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=players
      - POSTGRES_USER=postgres
    ports: 
      - "5433:5432"
    image: postgres:10-alpine
    volumes: 
      - db-data:/var/lib/postgresql/data

volumes: 
  db-data: